export class Constants {
    // common section
    DISCORD_BOT_TOKEN: string;
    DISCORD_BOT_ADMIN_USER_ID: string;
    DISCORD_LATEST_LIST_LENGTH: number;
    DISCORD_FOLLOW_MINUTE: number;
    DISCORD_FOLLOW_CRON: string;
    DISCORD_UPDATE_CHANNEL_NAME_CRON: string;
    DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE: number;
    DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE_SQL: string;
    DEV_MODE: boolean;

    DISCORD_FRIEND_CODE_OTHER_COUNT: number;
    DISCORD_FRIEND_CODE_IGNORE_ROLE_LIST: string[];

    // sqlite section
    SQLITE_FILE: string;
    SQLITE_TEMPLATE_FILE: string;

    // export file section
    EXPORT_USER_INFO_PATH: string;

    // message section
    DISCORD_ACTIVITY_NAME: string;
    DISCORD_MESSAGE_IS_INVALID: string;
    DISCORD_MESSAGE_TYPE_INVALID: string;
    DISCORD_MESSAGE_NOT_FOUND_RECRUITMENT: string;
    DISCORD_MESSAGE_EXPORT_TITLE: string;
    DISCORD_MESSAGE_EXPORT_USER_INFO: string;
    DISCORD_MESSAGE_EXPORT_USER_INFO_LIMIT_EXCEEDED: string;
    DISCORD_MESSAGE_EXCEPTION: string;
    DISCORD_MESSAGE_TOKEN_GENERATE_LIMIT_EXCEEDED: string;
    DISCORD_MESSAGE_NO_PERMISSION: string;
    DISCORD_MESSAGE_COMMAND_IS_REGIST: string;
    DISCORD_MESSAGE_SETTING_IS_NOT_READY: string;
    DISCORD_MESSAGE_SETTING_ROLE_SELECT: string;
    DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_REGIST_FRIEND_CODE: string;
    DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_SEARCH_FRIEND_CODE: string;
    DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_DELETE_FRIEND_CODE: string;

    DISCORD_FRIEND_CODE_OTHER_NAME_FORMAT: string;
    DISCORD_RECRUITMENT_MODAL_TIME: string;
    DISCORD_RECRUITMENT_MODAL_DESCRIPTION: string;
    DISCORD_FRIEND_CODE_MODAL_FRIEND_CODE: string;

    DISCORD_MESSAGE_TITLE_NEW_RECRUITMENT: string;
    DISCORD_MESSAGE_NEW_RECRUITMENT: string;
    DISCORD_MESSAGE_TITLE_EDIT_RECRUITMENT: string;
    DISCORD_MESSAGE_EDIT_RECRUITMENT: string;
    DISCORD_MESSAGE_TITLE_DELETE_RECRUITMENT: string;
    DISCORD_MESSAGE_DELETE_RECRUITMENT: string;
    DISCORD_MESSAGE_TITLE_SUCCESS_JOIN: string;
    DISCORD_MESSAGE_SUCCESS_JOIN: string;
    DISCORD_MESSAGE_TITLE_SUCCESS_VIEW: string;
    DISCORD_MESSAGE_SUCCESS_VIEW: string;
    DISCORD_MESSAGE_TITLE_SUCCESS_DECLINE: string;
    DISCORD_MESSAGE_SUCCESS_DECLINE: string;
    DISCORD_MESSAGE_TITLE_FOLLOW_RECRUITMENT: string;
    DISCORD_MESSAGE_FOLLOW_RECRUITMENT: string;
    DISCORD_MESSAGE_REGIST_SERVER_INFO: string;
    DISCORD_MESSAGE_REGIST_FRIEND_CODE: string;
    DISCORD_MESSAGE_SEARCH_FRIEND_CODE: string;
    DISCORD_MESSAGE_SEARCH_FRIEND_CODE_NOT_FOUND: string;
    DISCORD_MESSAGE_DELETE_FRIEND_CODE: string;
    DISCORD_MESSAGE_DELETE_FRIEND_CODE_NOT_FOUND: string;

    DISOCRD_UPDATE_CHANNEL_NAME_FORMAT: string;
    DISOCRD_UPDATE_CHANNEL_NAME_FORMAT_REGEXP: string;

    DISCORD_BUTTUN_JOIN: string;
    DISCORD_BUTTON_DECLINE: string;
    DISCORD_BUTTON_VIEW: string;

    DISCORD_EXPORT_USER_INFO_SPLIT_CHAR: string;
    DISCORD_EXPORT_USER_INFO_LINE_SEPARATOR: string;
    DISCORD_EXPORT_USER_INFO_NAME_ITEM_NAME: string;
    DISCORD_EXPORT_USER_INFO_NAME_ITEM_ID: string;
    DISCORD_EXPORT_USER_INFO_HAS_ROLE: string;
    DISCORD_EXPORT_USER_INFO_NO_ROLE: string;

    DISCORD_COMMAND_NEW_RECRUITMENT: string;
    DISCORD_COMMAND_EDIT_RECRUITMENT: string;
    DISCORD_COMMAND_DELETE_RECRUITMENT: string;
    DISCORD_COMMAND_LIST_RECRUITMENT: string;
    DISCORD_COMMAND_REGIST_MASTER: string;
    DISCORD_COMMAND_REGIST_COMMAND: string;
    DISCORD_COMMAND_USER_INFO_LIST_GET: string;
    DISCORD_COMMAND_SEARCH_FRIEND_CODE: string;
    DISCORD_COMMAND_REGIST_FRIEND_CODE: string;
    DISCORD_COMMAND_DELETE_FRIEND_CODE: string;

    DISCORD_COMMAND_DESCRIPTION_NEW_RECRUITMENT: string;
    DISCORD_COMMAND_DESCRIPTION_EDIT_RECRUITMENT: string;
    DISCORD_COMMAND_DESCRIPTION_DELETE_RECRUITMENT: string;
    DISCORD_COMMAND_DESCRIPTION_LIST_RECRUITMENT: string;
    DISCORD_COMMAND_DESCRIPTION_REGIST_MASTER: string;
    DISCORD_COMMAND_DESCRIPTION_USER_INFO_LIST_GET: string;
    DISCORD_COMMAND_DESCRIPTION_SEARCH_FRIEND_CODE: string;
    DISCORD_COMMAND_DESCRIPTION_REGIST_FRIEND_CODE: string;

    DISCORD_COMMAND_EXCEPT_WORDS_OF_TIME: string[];

    // message static values section
    DISCORD_MESSAGE_EMBED_NO_MEMBER: string;
    DISCORD_MESSAGE_EMBED_TITLE: string;
    DISCORD_MESSAGE_EMBED_OWNER: string;
    DISCORD_MESSAGE_EMBED_START_TIME: string;
    DISCORD_MESSAGE_EMBED_JOIN_MEMBERS: string;
    DISCORD_MESSAGE_EMBED_VIEW_MEMBERS: string;

    // static values
    ID_INVALID: number;

    TYPE_INIT: number;
    TYPE_RECRUITEMENT: number;
    TYPE_JOIN: number;
    TYPE_DECLINE: number;
    TYPE_LIST: number;
    TYPE_REGIST_MAETER: number;
    TYPE_USER_INFO_LIST_GET: number;
    TYPE_VIEW: number;
    TYPE_EDIT: number;
    TYPE_DELETE: number;

    STATUS_DISABLED: number;
    STATUS_ENABLED: number;
    STATUS_VIEW: number;

    USER_INFO_LIST_LIMIT_NUMBER: number;
    DiSCORD_SELECT_MENU_LIMIT_LENGTH: number;

    DISCORD_MODAL_CUSTOM_ID_NEW_RECRUITMENT: string;
    DISCORD_MODAL_CUSTOM_ID_EDIT_RECRUITMENT: string;
    DISCORD_MODAL_CUSTOM_ID_DELETE_RECRUITMENT: string;
    DISCORD_MODAL_CUSTOM_ID_LIST_RECRUITMENT: string;
    DISCORD_SELECT_MENU_CUSTOM_ID_REGIST_SERVER_MASTER: string;
    DISCORD_MODAL_CUSTOM_ID_EXPORT_RECRUITMENT: string;
    DISCORD_SELECT_MENU_CUSTOM_ID_FOR_SEARCH_FRIEND_CODE_BY_GAME_NAME_LIST: string;
    DISCORD_SELECT_MENU_CUSTOM_ID_FOR_REGIST_FRIEND_CODE_BY_GAME_NAME_LIST: string;
    DISCORD_SELECT_MENU_CUSTOM_ID_FOR_DELETE_FRIEND_CODE_BY_GAME_NAME_LIST: string;
    DISCORD_MODAL_CUSTOM_ID_REGIST_FRIEND_CODE: string;

    DISCORD_MODAL_TIME_ID: string;
    DISCORD_MODAL_DESCRIPTION_ID: string;
    DISCORD_MODAL_FRIEND_CODE_ID: string;

    RECRUITMENT_DEFAULT_LIMIT_HOURS: number;
    RECRUITMENT_DEFAULT_MAX_NUMBERS: number;
    RECRUITMENT_INVALID_CHANNEL_ID: string;
    RECRUITMENT_INVALID_ROLE: string;
    RECRUITMENT_DEFAULT_DESCRIPTION: string;

    DISCORD_BUTTON_ID_JOIN_RECRUITMENT_PREFIX: string;
    DISCORD_BUTTON_ID_DECLINE_RECRUITMENT_PREFIX: string;
    DISCORD_BUTTON_ID_VIEW_RECRUITMENT_PREFIX: string;

    ERROR_RECRUITMENT_TOKEN: string;

    REQUIRE_NAME_SQLITE3: string;

    static STRING_EMPTY = '';

    /**
     * constructor, set all value from process.env
     * @constructor
     */
    constructor() {
        // readed from env file
        require('dotenv').config();

        // common section
        this.DISCORD_BOT_TOKEN = process.env['DISCORD_BOT_TOKEN'] || Constants.STRING_EMPTY;
        this.DISCORD_BOT_ADMIN_USER_ID = process.env['DISCORD_BOT_ADMIN_USER_ID'] || Constants.STRING_EMPTY;
        this.DISCORD_LATEST_LIST_LENGTH = parseInt(process.env['DISCORD_LATEST_LIST_LENGTH'] || Constants.STRING_EMPTY);
        if (isNaN(this.DISCORD_LATEST_LIST_LENGTH)) {
            // set default
            this.DISCORD_LATEST_LIST_LENGTH = 3;
        }
        this.DISCORD_FOLLOW_MINUTE = parseInt(process.env['DISCORD_FOLLOW_MINUTE'] || Constants.STRING_EMPTY);
        if (isNaN(this.DISCORD_FOLLOW_MINUTE)) {
            // set default
            this.DISCORD_FOLLOW_MINUTE = 30;
        }
        this.DISCORD_FOLLOW_CRON = process.env['DISCORD_FOLLOW_CRON'] || Constants.STRING_EMPTY;
        this.DISCORD_UPDATE_CHANNEL_NAME_CRON = process.env['DISCORD_UPDATE_CHANNEL_NAME_CRON'] || Constants.STRING_EMPTY;
        this.DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE = parseInt(process.env['DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE'] || Constants.STRING_EMPTY);
        if (isNaN(this.DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE)) {
            // set default
            this.DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE = 0;
        }
        // create sql strings
        this.DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE_SQL = `-${this.DISCORD_RECRUITMENT_EXPIRE_DELAY_MINUTE} minutes`;
        // get dev mode
        if (process.env['DEV_MODE'] != undefined && process.env['DEV_MODE'].toLowerCase() == 'true') {
            this.DEV_MODE = true;
        } else {
            this.DEV_MODE = false;
        }

        this.DISCORD_FRIEND_CODE_OTHER_NAME_FORMAT = process.env['DISCORD_FRIEND_CODE_OTHER_NAME_FORMAT'] || Constants.STRING_EMPTY;
        this.DISCORD_FRIEND_CODE_OTHER_COUNT = parseInt(process.env['DISCORD_FRIEND_CODE_OTHER_COUNT'] || Constants.STRING_EMPTY);
        if (isNaN(this.DISCORD_FRIEND_CODE_OTHER_COUNT)) {
            // set default
            this.DISCORD_FRIEND_CODE_OTHER_COUNT = 0;
        }
        this.DISCORD_FRIEND_CODE_IGNORE_ROLE_LIST = process.env['DISCORD_FRIEND_CODE_IGNORE_ROLE_LIST']?.split(',') || [];

        // sqlite section
        this.SQLITE_FILE = process.env['SQLITE_FILE'] || Constants.STRING_EMPTY;
        this.SQLITE_TEMPLATE_FILE = process.env['SQLITE_TEMPLATE_FILE'] || Constants.STRING_EMPTY;

        // export file section
        this.EXPORT_USER_INFO_PATH = process.env['EXPORT_USER_INFO_PATH'] || Constants.STRING_EMPTY;

        // message section
        this.DISCORD_ACTIVITY_NAME = process.env['DISCORD_ACTIVITY_NAME'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_IS_INVALID = process.env['DISCORD_MESSAGE_IS_INVALID'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TYPE_INVALID = process.env['DISCORD_MESSAGE_TYPE_INVALID'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_NOT_FOUND_RECRUITMENT = process.env['DISCORD_MESSAGE_NOT_FOUND_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EXPORT_TITLE = process.env['DISCORD_MESSAGE_EXPORT_TITLE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EXPORT_USER_INFO = process.env['DISCORD_MESSAGE_EXPORT_USER_INFO'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EXPORT_USER_INFO_LIMIT_EXCEEDED = process.env['DISCORD_MESSAGE_EXPORT_USER_INFO_LIMIT_EXCEEDED'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EXCEPTION = process.env['DISCORD_MESSAGE_EXCEPTION'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TOKEN_GENERATE_LIMIT_EXCEEDED = process.env['DISCORD_MESSAGE_TOKEN_GENERATE_LIMIT_EXCEEDED'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_NO_PERMISSION = process.env['DISCORD_MESSAGE_NO_PERMISSION'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_COMMAND_IS_REGIST = process.env['DISCORD_MESSAGE_COMMAND_IS_REGIST'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SETTING_IS_NOT_READY = process.env['DISCORD_MESSAGE_SETTING_IS_NOT_READY'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SETTING_ROLE_SELECT = process.env['DISCORD_MESSAGE_SETTING_ROLE_SELECT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_REGIST_FRIEND_CODE = process.env['DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_REGIST_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_SEARCH_FRIEND_CODE = process.env['DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_SEARCH_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_DELETE_FRIEND_CODE = process.env['DISCORD_MESSAGE_SELECT_GAME_MASTER_FOR_DELETE_FRIEND_CODE'] || Constants.STRING_EMPTY;

        this.DISCORD_RECRUITMENT_MODAL_TIME = process.env['DISCORD_RECRUITMENT_MODAL_TIME'] || Constants.STRING_EMPTY;
        this.DISCORD_RECRUITMENT_MODAL_DESCRIPTION = process.env['DISCORD_RECRUITMENT_MODAL_DESCRIPTION'] || Constants.STRING_EMPTY;
        this.DISCORD_FRIEND_CODE_MODAL_FRIEND_CODE = process.env['DISCORD_FRIEND_CODE_MODAL_FRIEND_CODE'] || Constants.STRING_EMPTY;

        this.DISCORD_MESSAGE_TITLE_NEW_RECRUITMENT = process.env['DISCORD_MESSAGE_TITLE_NEW_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_NEW_RECRUITMENT = process.env['DISCORD_MESSAGE_NEW_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TITLE_EDIT_RECRUITMENT = process.env['DISCORD_MESSAGE_TITLE_EDIT_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EDIT_RECRUITMENT = process.env['DISCORD_MESSAGE_EDIT_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TITLE_DELETE_RECRUITMENT = process.env['DISCORD_MESSAGE_TITLE_DELETE_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_DELETE_RECRUITMENT = process.env['DISCORD_MESSAGE_DELETE_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TITLE_SUCCESS_JOIN = process.env['DISCORD_MESSAGE_TITLE_SUCCESS_JOIN'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SUCCESS_JOIN = process.env['DISCORD_MESSAGE_SUCCESS_JOIN'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TITLE_SUCCESS_VIEW = process.env['DISCORD_MESSAGE_TITLE_SUCCESS_VIEW'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SUCCESS_VIEW = process.env['DISCORD_MESSAGE_SUCCESS_VIEW'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TITLE_SUCCESS_DECLINE = process.env['DISCORD_MESSAGE_TITLE_SUCCESS_DECLINE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SUCCESS_DECLINE = process.env['DISCORD_MESSAGE_SUCCESS_DECLINE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_TITLE_FOLLOW_RECRUITMENT = process.env['DISCORD_MESSAGE_TITLE_FOLLOW_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_FOLLOW_RECRUITMENT = process.env['DISCORD_MESSAGE_FOLLOW_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_REGIST_SERVER_INFO = process.env['DISCORD_MESSAGE_REGIST_SERVER_INFO'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_REGIST_FRIEND_CODE = process.env['DISCORD_MESSAGE_REGIST_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SEARCH_FRIEND_CODE = process.env['DISCORD_MESSAGE_SEARCH_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_SEARCH_FRIEND_CODE_NOT_FOUND = process.env['DISCORD_MESSAGE_SEARCH_FRIEND_CODE_NOT_FOUND'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_DELETE_FRIEND_CODE = process.env['DISCORD_MESSAGE_DELETE_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_DELETE_FRIEND_CODE_NOT_FOUND = process.env['DISCORD_MESSAGE_DELETE_FRIEND_CODE_NOT_FOUND'] || Constants.STRING_EMPTY;

        this.DISCORD_BUTTUN_JOIN = process.env['DISCORD_BUTTUN_JOIN'] || Constants.STRING_EMPTY;
        this.DISCORD_BUTTON_DECLINE = process.env['DISCORD_BUTTON_DECLINE'] || Constants.STRING_EMPTY;
        this.DISCORD_BUTTON_VIEW = process.env['DISCORD_BUTTON_VIEW'] || Constants.STRING_EMPTY;

        this.DISCORD_EXPORT_USER_INFO_SPLIT_CHAR = process.env['DISCORD_EXPORT_USER_INFO_SPLIT_CHAR'] || Constants.STRING_EMPTY;
        this.DISCORD_EXPORT_USER_INFO_LINE_SEPARATOR = process.env['DISCORD_EXPORT_USER_INFO_LINE_SEPARATOR'] || Constants.STRING_EMPTY;
        this.DISCORD_EXPORT_USER_INFO_NAME_ITEM_NAME = process.env['DISCORD_EXPORT_USER_INFO_NAME_ITEM_NAME'] || Constants.STRING_EMPTY;
        this.DISCORD_EXPORT_USER_INFO_NAME_ITEM_ID = process.env['DISCORD_EXPORT_USER_INFO_NAME_ITEM_ID'] || Constants.STRING_EMPTY;
        this.DISCORD_EXPORT_USER_INFO_HAS_ROLE = process.env['DISCORD_EXPORT_USER_INFO_HAS_ROLE'] || Constants.STRING_EMPTY;
        this.DISCORD_EXPORT_USER_INFO_NO_ROLE = process.env['DISCORD_EXPORT_USER_INFO_NO_ROLE'] || Constants.STRING_EMPTY;

        this.DISCORD_COMMAND_NEW_RECRUITMENT = process.env['DISCORD_COMMAND_NEW_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_EDIT_RECRUITMENT = process.env['DISCORD_COMMAND_EDIT_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DELETE_RECRUITMENT = process.env['DISCORD_COMMAND_DELETE_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_LIST_RECRUITMENT = process.env['DISCORD_COMMAND_LIST_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_REGIST_MASTER = process.env['DISCORD_COMMAND_REGIST_MASTER'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_REGIST_COMMAND = process.env['DISCORD_COMMAND_REGIST_COMMAND'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_USER_INFO_LIST_GET = process.env['DISCORD_COMMAND_USER_INFO_LIST_GET'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_SEARCH_FRIEND_CODE = process.env['DISCORD_COMMAND_SEARCH_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_REGIST_FRIEND_CODE = process.env['DISCORD_COMMAND_REGIST_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DELETE_FRIEND_CODE = process.env['DISCORD_COMMAND_DELETE_FRIEND_CODE'] || Constants.STRING_EMPTY;

        this.DISCORD_COMMAND_DESCRIPTION_NEW_RECRUITMENT = process.env['DISCORD_COMMAND_DESCRIPTION_NEW_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DESCRIPTION_EDIT_RECRUITMENT = process.env['DISCORD_COMMAND_DESCRIPTION_EDIT_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DESCRIPTION_DELETE_RECRUITMENT = process.env['DISCORD_COMMAND_DESCRIPTION_DELETE_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DESCRIPTION_LIST_RECRUITMENT = process.env['DISCORD_COMMAND_DESCRIPTION_LIST_RECRUITMENT'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DESCRIPTION_REGIST_MASTER = process.env['DISCORD_COMMAND_DESCRIPTION_REGIST_MASTER'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DESCRIPTION_USER_INFO_LIST_GET = process.env['DISCORD_COMMAND_DESCRIPTION_USER_INFO_LIST_GET'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DESCRIPTION_SEARCH_FRIEND_CODE = process.env['DISCORD_COMMAND_DESCRIPTION_SEARCH_FRIEND_CODE'] || Constants.STRING_EMPTY;
        this.DISCORD_COMMAND_DESCRIPTION_REGIST_FRIEND_CODE = process.env['DISCORD_COMMAND_DESCRIPTION_REGIST_FRIEND_CODE'] || Constants.STRING_EMPTY;

        this.DISOCRD_UPDATE_CHANNEL_NAME_FORMAT = process.env['DISOCRD_UPDATE_CHANNEL_NAME_FORMAT'] || Constants.STRING_EMPTY;
        this.DISOCRD_UPDATE_CHANNEL_NAME_FORMAT_REGEXP = process.env['DISOCRD_UPDATE_CHANNEL_NAME_FORMAT_REGEXP'] || Constants.STRING_EMPTY;

        this.DISCORD_COMMAND_EXCEPT_WORDS_OF_TIME = process.env['DISCORD_COMMAND_EXCEPT_WORDS_OF_TIME']?.split(',') || [];

        // message static values section
        this.DISCORD_MESSAGE_EMBED_NO_MEMBER = process.env['DISCORD_MESSAGE_EMBED_NO_MEMBER'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EMBED_TITLE = process.env['DISCORD_MESSAGE_EMBED_TITLE'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EMBED_OWNER = process.env['DISCORD_MESSAGE_EMBED_OWNER'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EMBED_START_TIME = process.env['DISCORD_MESSAGE_EMBED_START_TIME'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EMBED_JOIN_MEMBERS = process.env['DISCORD_MESSAGE_EMBED_JOIN_MEMBERS'] || Constants.STRING_EMPTY;
        this.DISCORD_MESSAGE_EMBED_VIEW_MEMBERS = process.env['DISCORD_MESSAGE_EMBED_VIEW_MEMBERS'] || Constants.STRING_EMPTY;

        // static values
        this.ID_INVALID = -1;

        this.TYPE_INIT = 0;
        this.TYPE_RECRUITEMENT = 1;
        this.TYPE_JOIN = 2;
        this.TYPE_DECLINE = 3;
        this.TYPE_LIST = 4;
        this.TYPE_REGIST_MAETER = 21;
        this.TYPE_USER_INFO_LIST_GET = 31;
        this.TYPE_VIEW = 5;
        this.TYPE_EDIT = 6;
        this.TYPE_DELETE = 7;

        this.STATUS_DISABLED = 0;
        this.STATUS_ENABLED = 1;
        this.STATUS_VIEW = 2;

        this.USER_INFO_LIST_LIMIT_NUMBER = 1000;
        this.DiSCORD_SELECT_MENU_LIMIT_LENGTH = 25;

        this.DISCORD_MODAL_CUSTOM_ID_NEW_RECRUITMENT = 'REQRUITMENT_MODAL_NEW_RECRUITMENT';
        this.DISCORD_MODAL_CUSTOM_ID_EDIT_RECRUITMENT = 'REQRUITMENT_MODAL_EDIT_RECRUITMENT';
        this.DISCORD_MODAL_CUSTOM_ID_DELETE_RECRUITMENT = 'REQRUITMENT_MODAL_DELETE_RECRUITMENT';
        this.DISCORD_MODAL_CUSTOM_ID_LIST_RECRUITMENT = 'REQRUITMENT_MODAL_LIST_RECRUITMENT';
        this.DISCORD_SELECT_MENU_CUSTOM_ID_REGIST_SERVER_MASTER = 'REQRUITMENT_MODAL_REGIST_RECRUITMENT';
        this.DISCORD_MODAL_CUSTOM_ID_EXPORT_RECRUITMENT = 'REQRUITMENT_MODAL_EXPORT_RECRUITMENT';
        this.DISCORD_SELECT_MENU_CUSTOM_ID_FOR_SEARCH_FRIEND_CODE_BY_GAME_NAME_LIST = 'DISCORD_SELECT_MENU_CUSTOM_ID_FOR_SEARCH_FRIEND_CODE_BY_GAME_NAME_LIST';
        this.DISCORD_SELECT_MENU_CUSTOM_ID_FOR_REGIST_FRIEND_CODE_BY_GAME_NAME_LIST = 'DISCORD_SELECT_MENU_CUSTOM_ID_FOR_REGIST_FRIEND_CODE_BY_GAME_NAME_LIST';
        this.DISCORD_SELECT_MENU_CUSTOM_ID_FOR_DELETE_FRIEND_CODE_BY_GAME_NAME_LIST = 'DISCORD_SELECT_MENU_CUSTOM_ID_FOR_DELETE_FRIEND_CODE_BY_GAME_NAME_LIST';
        this.DISCORD_MODAL_CUSTOM_ID_REGIST_FRIEND_CODE = 'DISCORD_MODAL_CUSTOM_ID_REGIST_FRIEND_CODE';

        this.DISCORD_MODAL_TIME_ID = 'time';
        this.DISCORD_MODAL_DESCRIPTION_ID = 'description';
        this.DISCORD_MODAL_FRIEND_CODE_ID = 'friend-code';

        this.RECRUITMENT_DEFAULT_LIMIT_HOURS = 8;
        this.RECRUITMENT_DEFAULT_MAX_NUMBERS = 6;
        this.RECRUITMENT_INVALID_CHANNEL_ID = 'TARGET_CHANNEL_ID_IS_NOT_FOUND';
        this.RECRUITMENT_INVALID_ROLE = 'TARGET_ROLE_IS_NOT_FOUND';
        this.RECRUITMENT_DEFAULT_DESCRIPTION = 'joined by interaction button.';

        this.DISCORD_BUTTON_ID_JOIN_RECRUITMENT_PREFIX = 'join-recruite-token=';
        this.DISCORD_BUTTON_ID_DECLINE_RECRUITMENT_PREFIX = 'decline-recruite-token=';
        this.DISCORD_BUTTON_ID_VIEW_RECRUITMENT_PREFIX = 'view-recruite-token=';

        this.ERROR_RECRUITMENT_TOKEN = 'ERROR_TOKEN';

        this.REQUIRE_NAME_SQLITE3 = 'sqlite3';
    }

    /**
     * get default data for this system
     * @returns date instance of '2000-01-01 00:00:00'
     */
    static get_default_date(): Date {
        const temp_date = new Date();
        temp_date.setFullYear(2000);
        temp_date.setMonth(0);
        temp_date.setDate(1);
        temp_date.setHours(0);
        temp_date.setMinutes(0);
        temp_date.setSeconds(0);
        temp_date.setMilliseconds(0);

        return temp_date;
    }

    /**
     * escape string for regexp (e.g. escape user input string)
     * @param v regexp string non-escaped
     * @returns escaped regexp string
     */
    static escape_regexp(v: string) {
        return v.replace(/[.*+?^=!:${}()|[\]\/\\]/g, '\\$&');
    }
};